### ISSUE TITLE
Cannot register for iOS

### ISSUE THREAD

**Issue by bwatabu** [Pushwoosh/pushwoosh-corona-sdk#1]
After configuring pushwoosh with my corona application, I found that the function pushwoosh.registerForPushNotifications has a condition that will never get entered and will not allow iOS users to access their pushwoosh notifications.  Instead of:

if ( system.getInfo("platformName") == "iPhone OS" ) then

it should be

if ( system.getInfo("platformName") == "iOS" ) then

this is on line 165.  Fixing this condition block will allow iOS users to register for their push applications.

**Comment by viridanti** [comment]
Hi,

Thanks a lot. Will be fixed soon.

**Comment by DimanAM** [comment]
Cannot reproduce this problem. iOS build works just fine on current (2016.2992) Corona SDK version.

And according to https://docs.coronalabs.com/api/library/system/getInfo.html
```lua
system.getInfo("platformName") == "iPhone OS"
``` 
is the correct iOS `platformName` check. However `platformName` option appears to be deprecated. So I have changed it to `platform`.
